blank_issues_enabled: false
contact_links:
  - name: ğŸ†˜ Support Technique
    url: https://github.com/vortechstudio/Batistack/discussions/categories/support
    about: Obtenir de l'aide sur la configuration ou l'utilisation
  - name: ğŸ’¡ Suggestions de Modules
    url: https://github.com/vortechstudio/Batistack/discussions/categories/ideas
    about: Proposer une amÃ©lioration de module existant

templates:
  - name: "ğŸ› Bug Report"
    description: "Signaler un problÃ¨me technique"
    labels: ['bug']
    body: "bug_report.yml"

  - name: "âœ¨ Feature Request"
    description: "Proposer une nouvelle fonctionnalitÃ©"
    labels: ['feature']
    body: "feature_request.yml"

  - name: "Module: Core"
    description: "Issue liÃ©e au module Core"
    labels: ['module:core']
    body: "core.yml"
